use sakila;

-- DCL (DATA CONTROL LANGUAGE)
-- AUTHENTICATION,AUTHORIZATION
CREATE USER BOB12 IDENTIFIED BY 'BOB';
SELECT * FROM MYSQL.USER;
-- CURRENT
SELECT current_user();
SHOW GRANTS FOR 'BOB12';

-- 
CREATE USER 'SAMMY'@'192.16.10.%' IDENTIFIED BY 'PASSWORD';
-- permission
grant all privileges on sakila.* to BOB12;
show grants for 'BOB12';
-- FOR CHANGE PASSWORD
ALTER USER 'BOB12' IDENTIFIED BY 'REGEX';
-- LOCKING USER
ALTER USER 'BOB12' ACCOUNT LOCK;
-- UNLOCK
ALTER USER 'BOB12' ACCOUNT UNLOCK;
-- ROLES IS SIMPLY A GROUP
-- CREATING ROLES
CREATE ROLE SALES;
GRANT SELECT ON SAKILA.* TO SALES;

CREATE USER 'AMAN' IDENTIFIED BY 'AMAN';
SHOW GRANTS FOR 'AMAN';

GRANT SALES TO 'AMAN';
SHOW GRANTS FOR 'AMAN';

-- ASSIGN ROLE TO USER
SET default role ALL TO AMAN;

USE SAKILA;

CREATE TABLE DESERT(
    ID INT,
    ENAME VARCHAR (50)
);
SELECT * FROM DESERT;
